export enum TransferReason {
  SALE = 'SALE',

  PURCHASE = 'PURCHASE',

  CONSIGNMENT = 'CONSIGNMENT',

  RETURN = 'RETURN',

  TRANSFORMATION = 'TRANSFORMATION',

  BETWEEN_ESTABLISHMENTS = 'BETWEEN_ESTABLISHMENTS',

  PICKUP = 'PICKUP',

  ITINERANT_ISSUER = 'ITINERANT_ISSUER',

  PRIMARY_ZONE = 'PRIMARY_ZONE',

  IMPORT = 'IMPORT',

  EXPORT = 'EXPORT',

  OTHER = 'OTHER',
}
